### ISSUE TITLE
Poetry + Jupyter

### ISSUE THREAD

**Issue by setegonz** [petobens/introduccion-ml-aplicado#2]
Hola.
Me gustaría saber cómo combinas Jupyter y Poetry. ¿Tu instalación de Jupyter es global o haces un ambiente virtual para añadir los paquetes de data science, jupyter incluido? ¿Debes tener un Kernel de jupyter en cada ambiente virtual? Agradeceré cualquier información adicional.

**Comment by petobens** [comment]
Hola! Si tenes instalado jupyter en un venv de poetry (por ejemplo mediante `poetry add jupyter --dev`) entonces deberia alcanzar con hacer `poetry run jupyter notebook` y eso te levanta jupyter con el kernel correcto.

**Comment by setegonz** [comment]
¿Inicias cada proyecto con `poetry add jupyter --dev`? ¿Eso significa que tienes la misma cantidad de instalaciones de jupyter como de proyectos?

**Comment by petobens** [comment]
A mi en general me gusta que cada proyecto tenga sus dependencias aisladas entonces efectivamente hago eso de un jupyter para cada proyecto.
